### ISSUE TITLE
Bug Dupe at economyland

### ISSUE THREAD

**Issue by Wildan-dev461** [iLVOEWOCK/AutoInventory#2]
Hi, can you fix this? this bug is same with tobias plugin and i hope you make a fork for EconomyLand to fix it

**Comment by iLVOEWOCK** [comment]
Can you explain more on what is happening?

**Comment by Wildan-dev461** [comment]
> Can you explain more on what is happening?

When you break a block on someone land, the item still going into inventory

**Comment by iLVOEWOCK** [comment]
what version of the plugin are you using?
if i recall correctly i fixed it in the latest version.

https://poggit.pmmp.io/p/AutoInventory/1.1.2

if you are could you show me your configuration?

**Comment by Wildan-dev461** [comment]
> what version of the plugin are you using? if i recall correctly i fixed it in the latest version.
> 
> https://poggit.pmmp.io/p/AutoInventory/1.1.2
> 
> if you are could you show me your configuration?

Latest version, yes you fix it in regionprotect, but maybe its not fixed for EconomyLand that i use

**Comment by iLVOEWOCK** [comment]
Could you send me the EconomyLand you use?

**Comment by Wildan-dev461** [comment]
> Could you send me the EconomyLand you use?

did you have a discord? i will send there

**Comment by iLVOEWOCK** [comment]
yes `woccck`

**Comment by Wildan-dev461** [comment]
> yes `woccck`

i've already send that on dm, thanks for you attention to this bug
